docs: pnpm 정리 추가
gdsc-ssu/2023-front-without-boilerplate pull request #3
Opened 2023-02-10 07:49 UTC by ballsona

패키지 매니저 Pnpm 정리 추가했습니다!
일정을 제대로 숙지하지 못해서 스터디 당일까지 정리하지 못한점 다시 한번 죄송합니다,,, 🥹🥹
늦은 만큼 더 열심히 정리해보았으나 추가하거나 수정할 부분이 있다면 알려주십쇼 !! 🤓

2023-02-11 06:06 UTC, kanghyun98 requested changes
정리 덕분에 pnpm과 pnpm이 어떻게 패키지 중복 설치 문제를 해결했는지에 대해 자세히 배울 수 있었어요! 감사합니다:)
(오타 몇개 찾아서 request changes를 해놨는데, 수정하시고 리뷰 재요청 해주시면 바로 approve 때리겠습니다ㅎ)

2023-02-11 06:06 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +**pnpm(performant npm)**은 Zoltan Kochan이 2017년에 내놓은 패키지 매니저이다.
bold 처리가 안됐습니다!

2023-02-11 06:06 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +기존 패키지 매니저에 비해 종속성 관리, 디스크 효율성, 속도 등의 관점에서 휼륭한 성능을 보이고 있는 [pnpm][https://pnpm.io/] 에 대해 알아보자.
pnpm 링크 처리가 안됐습니다!

2023-02-11 06:06 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +    [symlink된 node_modules 구조][https://pnpm.io/ko/symlinked-node-modules-structure]
여기도 링크 처리 안됐어요!

2023-02-11 06:06 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +> **하드링크(Hard Link)** : 심볼릭 링크와 달리, 하드링크는 원본 파일과 동일한 inode를 가지게 되므로, 원본 파일이 삭제되어도 링크된 파일은 여전히 사용 가능하다.
오호 친절한 설명 감사합니다:)

2023-02-11 06:06 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +​ 이와 의존 관계에 있는 패키지들은 `node_modules/.pnpm` 에 flat한 구조로 존재하게 된다.
정리하면 gdsc-pack 패키지와 관련된 모든 패키지가 .pnpm store에 중복성을 제거하고 설치되어 있는 상태인거고,
node_modules(.pnpm 포함)에서는 하드 링크(중복된 패키지는 심볼릭 링크)를 통해 실제 설치된 패키지를 가리키는 형태로 패키지 목록을 관리하여 중복성을 제거하는 방법이다.

제가 이해한 방식이 맞을까요?ㅎ

2023-02-11 06:06 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +- 모듈 설치 및 실행 속도가 매우 빠르다. 다른 패키지 매니저들과 비교했을 때에도 설치 속도가 빠른 편임을 확인할 수 있다.
pnpm이 yarn처럼 설치 프로세스를 병렬화했다는 내용은 못찾겠는데, 단순히 패키지 중복 설치를 제거해서 빠른걸까요..?

2023-02-11 09:35 UTC, seohyun319 approved these changes

2023-02-11 09:36 UTC, seohyun319 commented on 01. package-manager/03. PNPM.md
> +기존 패키지 매니저에 비해 종속성 관리, 디스크 효율성, 속도 등의 관점에서 휼륭한 성능을 보이고 있는 [pnpm][https://pnpm.io/] 에 대해 알아보자.
참고로 [pnpm](링크) 이런 식으로 하셔야 해요!

2023-02-15 03:14 UTC, ballsona commented on 01. package-manager/03. PNPM.md
> +​ 이와 의존 관계에 있는 패키지들은 `node_modules/.pnpm` 에 flat한 구조로 존재하게 된다.
네 강현님이 이해한 내용이 맞습니다!!

2023-02-15 03:29 UTC, ballsona commented on 01. package-manager/03. PNPM.md
> +- 모듈 설치 및 실행 속도가 매우 빠르다. 다른 패키지 매니저들과 비교했을 때에도 설치 속도가 빠른 편임을 확인할 수 있다.
네! 예를 들어 'gdsc-lib' 이라는 패키지를 사용하는 패키지들이 n개가 있다면 npm와 yarn은 최대 n개의 'gdsc-lib'을 모두 설치하게 되지만, pnpm 은 이를 1번만 설치 후 패키지들과 심링크로 연결되기 때문에 설치 속도나 용량 측면에서 높은 효율을 보이는 것 같아요! 

yarn처럼 설치 프로세스가 병렬화되는지는.. 열심히 서치해봤으나 저두 관련 글을 찾지는 못해서 혹시 알게되면 공유드리겠습니다 ..😅

2023-02-15 04:03 UTC, kanghyun98 commented on 01. package-manager/03. PNPM.md
> +- 모듈 설치 및 실행 속도가 매우 빠르다. 다른 패키지 매니저들과 비교했을 때에도 설치 속도가 빠른 편임을 확인할 수 있다.
오.. 친절한 답변 감사합니다!!😃

2023-02-15 11:57 UTC, kanghyun98 approved these changes

2023-02-16 05:37 UTC, yoo-jimin127 approved these changes
본의아니게 소나님께서 문서를 너무 잘 작성해주셔서, 
보고 피드백을 남긴 것이 아니라 감상평을 남긴 것 같네요 ㅋㅋㅋㅋ 
pnpm으로 모노레포를 구축하는 실습을 해보았었는데, 
그 때 제대로 알고 넘어가지 못했던 pnpm 디렉토리 구조나 의존성 관리를 어떻게 하는지 등
내부적인 원리를 한층 더 깊게 이해할 수 있었던 것 같습니다!
깔끔한 정리 하시느라 수고 많으셨어요!

2023-02-16 05:37 UTC, yoo-jimin127 commented on 01. package-manager/03. PNPM.md
> +- 이에 대안책으로 pnpm 은 **중첩된 `node_modules` 구조**를 채택했고, 의존성을 더욱 효과적으로 저장하기 위해 '내용 주소화 저장소(Content-addressable storage)' 방식을 사용한다.
저도 pnpm 조사하며서 유령 의존성, 플랫 알고리즘의 대안으로 `node_modules`를 중첩된 형태로 설계했다는 사실이 되게 신기하게 느껴졌던 것 같습니다 .. 개인공부하며 원리에 대해 더 자세하게 알아봐야겠어요!!

2023-02-16 05:37 UTC, yoo-jimin127 commented on 01. package-manager/03. PNPM.md
> +​ 이와 의존 관계에 있는 패키지들은 `node_modules/.pnpm` 에 flat한 구조로 존재하게 된다.
오 이부분이 되게 신기하고도 생소한 부분인 것 같아요! `.pnpm`이 이런 역할을 하다니 ,, 
소나님과 강현님 이해 내용으로 완벽히 와닿은 것 같습니다!

2023-02-16 05:37 UTC, yoo-jimin127 commented on 01. package-manager/03. PNPM.md
> +
으음 .. 저도 위에서 보면서 하드링크로 관리했을 때 부작용은 없을까 생각했었는데
역시나 호환성의 부분에서 문제가 발생하는군요 ..
진짜 패키지매니저별로 장단점이 확고한 것 같아서 알면 알수록 재밌네유!

2023-02-18 02:34 UTC, itjustbong approved these changes
깔끔한 정리 덕에 다시 한번 pnpm 살펴볼 수 있었습니다!!!
패키지매니저들 공부하다보면 자꾸 폴더 구조나 특징이 헷갈리는데,
tree 형태로 폴더 구조 기억해두면, 기억하는데 도움이 될 것 같네요!

저도 공부하면서 궁금했던 부분 댓글로 달아두었습니다!

정리 수고하셨습니당..🥳

2023-02-18 02:34 UTC, itjustbong commented on 01. package-manager/03. PNPM.md
> +​ 이와 의존 관계에 있는 패키지들은 `node_modules/.pnpm` 에 flat한 구조로 존재하게 된다.
오... 예시를 폴더 tree 로 가져와서 그런지 더 이해하기 좋네요!
gdsc-lib 라는 녀석을 설치했을 때, 나오는 node_modules 구조 인거죠?

2023-02-18 02:34 UTC, itjustbong commented on 01. package-manager/03. PNPM.md
> +- 모듈 설치 및 실행 속도가 매우 빠르다. 다른 패키지 매니저들과 비교했을 때에도 설치 속도가 빠른 편임을 확인할 수 있다.
pnpm의 라이브러리 설치 과정 중에,
실제 라이브러리 파일은 프로젝트의 폴더에 설치가 되는게 아니라,
컴퓨터의 `~/.pnpm` 에 저장되는 건가요...?

제가 이해할 때는 위 처럼 이해했는데,
제 컴퓨터에서 볼때는 안그런 것 같아서...ㅠ

2023-02-20 18:25 UTC, ballsona commented on 01. package-manager/03. PNPM.md
> +​ 이와 의존 관계에 있는 패키지들은 `node_modules/.pnpm` 에 flat한 구조로 존재하게 된다.
@itjustbong 넵 맞슴다!!!

2023-02-20 19:29 UTC, ballsona commented on 01. package-manager/03. PNPM.md
> +- 모듈 설치 및 실행 속도가 매우 빠르다. 다른 패키지 매니저들과 비교했을 때에도 설치 속도가 빠른 편임을 확인할 수 있다.
@itjustbong 
사실.. 이 글을 작성할 때 라이브러리들이 어디에 물리적으로 저장되는지 실제로 확인은 따로 하지 않았었는데, 물어봐주셔가지구 열심히 알아보았는데요! 아무리 `.pnpm-store` 을 찾아도 없길래 알아보니 pnpm의 v7.0.0 부터는 pnpm 글로벌 저장소 주소가 `~/.pnpm-store` 에서 `~/Library/pnpm/store` (맥북 기준) 으로 변경되었다고 합니다. [관련 글](https://stackoverflow.com/questions/55403775/how-to-get-pnpm-store-directory) 

해당 폴더에 들어가보니 요런식으로 알 수 없는? 형태로 설치 되어 있는 걸 확인할 수 있었어요! 
<img width="906" alt="스크린샷 2023-02-21 04 25 31" src="https://user-images.githubusercontent.com/67703882/220185237-c246d59a-4a4c-4cb6-84be-0f9ef548d292.png">
덕분에 저도 새로운 사실을 알게 되었네요,, 이부분은 바로 반영하겠습니다 :) 리뷰 감사함다 승우님 !!

2023-03-22 11:16 UTC, merged